language: java
services:
  - docker

jobs:
  include:
    - stage:
      addons:
        sonarcloud:
          organization: "serinkanasci"
          token:
script:
  - nvm clean verify sonar:sonar -Pcoverage -Dsonar