addons:
  sonarcloud:
    organization: "serinkanasci"
    token: $SECURE_RUBY # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=serinkanasci_sample-application-students
